name: Notify on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest || exit 1; else echo "No tests found, skipping."; fi

      - name: Send notification email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub Actions Pipeline #${{ github.run_number }}: ${{ github.repository }}"
          to: shujaatalee888@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: |
            The GitHub Actions pipeline for ${{ github.repository }} on branch ${{ github.ref }} has completed.
            Status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
